blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/anon987654321/pub3/security
    about: Please report security vulnerabilities privately
  - name: Question or Discussion
    url: https://github.com/anon987654321/pub3/discussions
    about: Ask questions or start discussions about the project
