name: Verify Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  verify-links:
    name: Verify Documentation Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Check internal links
        run: |
          echo "Checking internal documentation links..."
          
          # Check core docs still exist
          if [ ! -f "LICENSE" ]; then
            echo "ERROR: LICENSE not found"
            exit 1
          fi
          
          # Check archived docs exist
          for file in DEVELOPMENT.md CONTRIBUTING.md SECURITY.md CHANGELOG.md CODE_OF_CONDUCT.md OVERVIEW.md AUTHORS; do
            if [ ! -f "docs/archive/$file" ]; then
              echo "ERROR: $file not found in docs/archive/"
              exit 1
            fi
          done
          
          echo "✓ All referenced documentation files exist"
      
      - name: Verify documentation structure
        run: |
          echo "Verifying documentation structure..."
          
          required_files=(
            "README.md"
            "LICENSE"
            "master.json"
            ".gitignore"
            ".editorconfig"
          )
          
          archived_files=(
            "docs/archive/CONTRIBUTING.md"
            "docs/archive/CODE_OF_CONDUCT.md"
            "docs/archive/SECURITY.md"
            "docs/archive/DEVELOPMENT.md"
            "docs/archive/CHANGELOG.md"
            "docs/archive/OVERVIEW.md"
            "docs/archive/AUTHORS"
          )
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file not found"
              exit 1
            fi
            echo "✓ $file exists"
          done
          
          for file in "${archived_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Archived file $file not found"
              exit 1
            fi
            echo "✓ $file exists"
          done
          
          echo "✓ All required documentation files present"
